services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: study-nextjs-microcms-book-sample
    command: sleep infinity
    logging:
      driver: json-file
      options:
        max-size: '1m'
        max-file: '3'
    ports:
      - 0.0.0.0:3060:3000
    volumes:
      - ..:/home/node/workspace
      - ~/.gnupg:/home/node/.gnupg
    environment:
      - GPG_TTY=/dev/pts/0
